### ISSUE TITLE
a potentiel error in file tdd/Inheritance /example.py

### ISSUE THREAD

**Issue by Drihmia** [lowercase2/cohort_18_lls#1]
The super() function should be used without passing self as an argument

**Comment by Drihmia** [comment]
`class Trout(Fish):
    def __init__(self, water="freshwater"):
        super().__init__()
        self.water = water
`

**Comment by Drihmia** [comment]
```class Trout(Fish):
    def __init__(self, water="freshwater"):
        super().__init__()
        self.water = water
```

**Comment by lowercase2** [comment]
Hello I have added you as a collaborator, open a pull request and I will merge changes.

**Comment by Drihmia** [comment]
done

**Comment by lowercase2** [comment]
changes merged to master. All good.
